### ISSUE TITLE
IMPROVE - Select a Vehicle in Dashboard and Odometer

### ISSUE THREAD

**Issue by dogra25130** [mikaelacaron/Basic-Car-Maintenance#200]
## Describe the feature you want to improve
Select a Vehicle

When user hasn't added any vehicle we can ask user to add a vehicle before selecting one. Current screen feels a bit confusing as we are asking user to mandatorily add a vehicle even though he hasn't added any yet.

We can show a button saying `add vehicle` which will take user to the add vehicle screen

<img src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/32197474/741f1505-05dd-4342-8a92-527913dec6d3" width=300>

**Comment by dogra25130** [comment]
@mikaelacaron  Can I pick this one?

**Comment by mikaelacaron** [comment]
I don't want this to work in this way, actually related to #40 I want to have an onboarding UI where a person must create their first vehicle there, and then this issue wouldn't come up anymore because it would always be assumed a person will have a vehicle created

I'm thinking a different issue to create is to not let a person delete all their vehicles, if they tried to delete them all, they'd get an error. I'll make that issue now, and comment on it, if you want to work on that one

**Comment by dogra25130** [comment]
Sure, will start working on it.
So basically we will be showing an error alert saying that we can't delete all the vehicles.

**Comment by mikaelacaron** [comment]
@dogra25130 I'm going to close this issue, after creating #202 and note that I made the issue labeled `first-timers-only`, because this is an issue that I would like someone new to the repo to be able to work on, given the scope of the issue

**Comment by dogra25130** [comment]
sure. I didn't read you message and raised the PR. Closing the PR for someone else to try.

**Comment by mikaelacaron** [comment]
@dogra25130 thank you for understanding! Also see [Discussions](https://github.com/mikaelacaron/Basic-Car-Maintenance/discussions) if you have a bigger idea of a feature you want to work on, you can discuss it there
