### ISSUE TITLE
BUG - Icons preview in ChooseAppIconView not visible

### ISSUE THREAD

**Issue by maartinj** [mikaelacaron/Basic-Car-Maintenance#330]
## Describe the bug
* As mentioned in the topic of the bug, all alternative icons are not visible in `ChooseAppIconView` for some reason

## To Reproduce
1. Run the app
2. Tap `SettingsView`
3. Tap `Change App Icon`
4. See icons preview not visible

## Expected behavior
* Show all alternative icons in `ChooseAppIconView`

## Screenshots
<img src="https://github.com/user-attachments/assets/853dca4c-b0c4-4627-b0af-e5e7c31076d1" height="500">

## Device Info:
* Device: iPhone 15 Pro Simulator
* OS: iOS 17.5
* App Version v1.0(1)

**Comment by mitaligondaliya** [comment]
Could you please assign me?

**Comment by mitaligondaliya** [comment]
Hello @mikaelacaron I've spent some time investigating the bug, and it seems that displaying AppIcons using UIImage(named: String) is deprecated. We can now fetch app icon images through the **CFBundleIcons** property list, but this only returns icons at a limited size of 64x64. Another option would be to create a new image set for all the app icons.

Let me know which approach you’d prefer to proceed with.

Here are the reference links where I found the solutions.

https://forums.developer.apple.com/forums/thread/757162

https://stackoverflow.com/questions/77408262/why-cant-swiftuis-image-see-the-appicon-file

**Comment by mikaelacaron** [comment]
@mitaligondaliya 
I think returning 64x64 icons is totally fine!
Thanks for the links, very helpful!

Check that when they're shown on the view, the images won't scale up with dynamic type, cause then they'd start to get pixelated

**Comment by mitaligondaliya** [comment]
@mikaelacaron I tried accessing CFBundleIcons, and while it works for the primary app icon, it doesn't seem to work for alternate icons. It appears that, after the deprecation of accessing app icons via UIImage(named:) from the App Icon set, alternate icons can't be fetched dynamically from the asset catalog. Most suggestions point toward adding a preview of app icons as Image Sets or in-app usage, instead of relying on the App Icon set for displaying app icons within the app.

<img width="1680" alt="Screenshot 2024-10-10 at 6 21 33 PM" src="https://github.com/user-attachments/assets/0c879790-524d-4a05-b567-1e044b5c49d3">
