### ISSUE TITLE
IMPROVE - Events on the `DashboardView`

### ISSUE THREAD

**Issue by rramirez-dev** [mikaelacaron/Basic-Car-Maintenance#333]
## Describe the feature you want to improve
Reformat how events are displayed on the dashboard with notes and without notes.

## Describe alternatives you've considered
N/A
![EventDisplay](https://github.com/user-attachments/assets/a885dbc4-0e91-4da1-b66c-cf786eff8f8e)

**Comment by rramirez-dev** [comment]
You can assign this anyone who wants it.

**Comment by ashabooga** [comment]
Hi there! I'd love to take a crack at this.

**Comment by mikaelacaron** [comment]
@ashabooga looking at this again, don't use the word "due" with the date, because that's not exactly accurate, just use the date there, because "due" implies that it's more of a reminder and / or something that _will happen_ at that time, as opposed to _already happened_

so just use the date itself (formatted properly by the person's phone settings)

Thanks!

**Comment by ashabooga** [comment]
Hi @mikaelacaron - so sorry for taking a while to reach this, I have it all finished. Just as a final check, I was wondering if you wanted me to copy the visuals as in the image above or if you wanted me to replicate the visuals that are currently implemented in the OdometerRowView. Thanks!

**Comment by mikaelacaron** [comment]
@ashabooga  Use what's in the image in this issue!
